export default {
  VWGO20ME_5EDTA_6: [
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 961,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 516.67,
      vat: 103.33,
      defaultOption: 0,
      description: "Metallic paint",
      nonSpecificCostOption: "TRUE",
      categoryCode: 58,
      categoryDescription: "Exterior Body Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 1924,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 516.67,
      vat: 103.33,
      defaultOption: 0,
      description: "Pearlescent paint",
      nonSpecificCostOption: "TRUE",
      categoryCode: 58,
      categoryDescription: "Exterior Body Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 1977,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 829.17,
      vat: 165.83,
      defaultOption: 0,
      description: "Premium paint",
      nonSpecificCostOption: "TRUE",
      categoryCode: 58,
      categoryDescription: "Exterior Body Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 14752,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description: "Solid paint",
      nonSpecificCostOption: "TRUE",
      categoryCode: 58,
      categoryDescription: "Exterior Body Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 27336,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 516.67,
      vat: 103.33,
      defaultOption: 0,
      description: "Metallic - Reflex silver",
      nonSpecificCostOption: "FALSE",
      categoryCode: 44,
      categoryDescription: "Paint - Metallic"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 54645,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 516.67,
      vat: 103.33,
      defaultOption: 0,
      description: "Metallic - Atlantic blue",
      nonSpecificCostOption: "FALSE",
      categoryCode: 44,
      categoryDescription: "Paint - Metallic"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 64626,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 308.33,
      vat: 61.67,
      defaultOption: 0,
      description: "Special solid paint",
      nonSpecificCostOption: "TRUE",
      categoryCode: 58,
      categoryDescription: "Exterior Body Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 69465,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 516.67,
      vat: 103.33,
      defaultOption: 0,
      description: "Pearl - Deep black",
      nonSpecificCostOption: "FALSE",
      categoryCode: 74,
      categoryDescription: "Paint - Pearlescent"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 71081,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 516.67,
      vat: 103.33,
      defaultOption: 0,
      description: "Metallic - Indium grey",
      nonSpecificCostOption: "FALSE",
      categoryCode: 44,
      categoryDescription: "Paint - Metallic"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 92805,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 0,
      description: "Solid - Urano grey",
      nonSpecificCostOption: "FALSE",
      categoryCode: 45,
      categoryDescription: "Paint - Solid"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 95049,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 516.67,
      vat: 103.33,
      defaultOption: 0,
      description: "Metallic - Tungsten silver",
      nonSpecificCostOption: "FALSE",
      categoryCode: 44,
      categoryDescription: "Paint - Metallic"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 96002,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 308.33,
      vat: 61.67,
      defaultOption: 0,
      description: "Special solid - Pure white",
      nonSpecificCostOption: "FALSE",
      categoryCode: 75,
      categoryDescription: "Paint - Special"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 97192,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 829.17,
      vat: 165.83,
      defaultOption: 0,
      description: "Premium paint - Oryx White",
      nonSpecificCostOption: "FALSE",
      categoryCode: 75,
      categoryDescription: "Paint - Special"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 99520,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 308.33,
      vat: 61.67,
      defaultOption: 0,
      description: "Special solid - Tornado red",
      nonSpecificCostOption: "FALSE",
      categoryCode: 75,
      categoryDescription: "Paint - Special"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223847,
      ruleType: "OO",
      optionCode: 121755,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 516.67,
      vat: 103.33,
      defaultOption: 0,
      description: "Metallic - Cranberry red",
      nonSpecificCostOption: "FALSE",
      categoryCode: 44,
      categoryDescription: "Paint - Metallic"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223848,
      ruleType: "OO",
      optionCode: 95052,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1791.67,
      vat: 358.33,
      defaultOption: 0,
      description:
        "Vienna leather upholstery + perforated heated front sports seats with manually adjustable lumbar support",
      nonSpecificCostOption: "TRUE",
      categoryCode: 61,
      categoryDescription: "Interior Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223848,
      ruleType: "OO",
      optionCode: 95055,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1791.67,
      vat: 358.33,
      defaultOption: 0,
      description:
        "Vienna leather - Black + heated front sports seats with lumbar support",
      nonSpecificCostOption: "FALSE",
      categoryCode: 82,
      categoryDescription: "Trim - Leather"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223848,
      ruleType: "OO",
      optionCode: 99112,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description: "Zoom/micro cloth upholstery",
      nonSpecificCostOption: "TRUE",
      categoryCode: 61,
      categoryDescription: "Interior Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223848,
      ruleType: "OO",
      optionCode: 99121,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 0,
      description: "Zoom/micro cloth - Titan Black",
      nonSpecificCostOption: "FALSE",
      categoryCode: 81,
      categoryDescription: "Trim - Cloth"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223848,
      ruleType: "OO",
      optionCode: 99122,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 0,
      description: "Zoom/micro cloth - Shetland beige",
      nonSpecificCostOption: "FALSE",
      categoryCode: 81,
      categoryDescription: "Trim - Cloth"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223849,
      ruleType: "OO",
      optionCode: 127918,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 512.5,
      vat: 102.5,
      defaultOption: 0,
      description: "17 Karlskoga alloy wheel with anti theft wheel bolts",
      nonSpecificCostOption: "FALSE",
      categoryCode: 88,
      categoryDescription: "Wheels - Alloy"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223849,
      ruleType: "OO",
      optionCode: 127919,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 512.5,
      vat: 102.5,
      defaultOption: 0,
      description: "17 Madrid alloy wheel with anti theft wheel bolts",
      nonSpecificCostOption: "FALSE",
      categoryCode: 88,
      categoryDescription: "Wheels - Alloy"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223849,
      ruleType: "OO",
      optionCode: 134328,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description: "16 Woodstock alloy wheels with anti theft wheel bolts",
      nonSpecificCostOption: "FALSE",
      categoryCode: 88,
      categoryDescription: "Wheels - Alloy"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223850,
      ruleType: "IN",
      optionCode: 108763,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 729.17,
      vat: 145.83,
      defaultOption: 0,
      description: "Trailer assist steering with park assist",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223850,
      ruleType: "IN",
      optionCode: 133035,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 500,
      vat: 100,
      defaultOption: 0,
      description:
        "Park assist sensor controlled steering aid to assist parallel or bay parking features optical parking display via vehicle's infotainment system",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223851,
      ruleType: "OO",
      optionCode: 88218,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description: "TFT display screen",
      nonSpecificCostOption: "FALSE",
      categoryCode: 66,
      categoryDescription: "Driver Information"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223851,
      ruleType: "OO",
      optionCode: 93187,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 125,
      vat: 25,
      defaultOption: 0,
      description: "Multifunction colour display",
      nonSpecificCostOption: "FALSE",
      categoryCode: 66,
      categoryDescription: "Driver Information"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223851,
      ruleType: "OO",
      optionCode: 133036,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 437.5,
      vat: 87.5,
      defaultOption: 0,
      description:
        "Active information display - 12.3 high resolution TFT display",
      nonSpecificCostOption: "FALSE",
      categoryCode: 66,
      categoryDescription: "Driver Information"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223852,
      ruleType: "OO",
      optionCode: 83935,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description: "LED Headlights",
      nonSpecificCostOption: "FALSE",
      categoryCode: 71,
      categoryDescription: "Exterior Lights"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223852,
      ruleType: "OO",
      optionCode: 117648,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 291.67,
      vat: 58.33,
      defaultOption: 0,
      description: "LED headlights with dynamic curve lighting",
      nonSpecificCostOption: "FALSE",
      categoryCode: 71,
      categoryDescription: "Exterior Lights"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223852,
      ruleType: "OO",
      optionCode: 117649,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 291.67,
      vat: 58.33,
      defaultOption: 0,
      description: "LED headlights with dynamic light assist",
      nonSpecificCostOption: "FALSE",
      categoryCode: 71,
      categoryDescription: "Exterior Lights"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223856,
      ruleType: "OO",
      optionCode: 118096,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 470.83,
      vat: 94.17,
      defaultOption: 0,
      description:
        "Lane assist + High beam assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223856,
      ruleType: "OO",
      optionCode: 118097,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 554.17,
      vat: 110.83,
      defaultOption: 0,
      description:
        "Lane assist with dynamic light assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223856,
      ruleType: "OO",
      optionCode: 118098,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1033.33,
      vat: 206.67,
      defaultOption: 0,
      description:
        "Lane assist plus with dynamic light assist, emergency assist, rear traffic alert, side scan, traffic jam assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223856,
      ruleType: "OO",
      optionCode: 118099,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 945.83,
      vat: 189.17,
      defaultOption: 0,
      description:
        "Lane assist plus with emergency assist, high beam assist, rear traffic alert, side scan, traffic jam assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223857,
      ruleType: "RA",
      optionCode: 117649,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 291.67,
      vat: 58.33,
      defaultOption: 0,
      description: "LED headlights with dynamic light assist",
      nonSpecificCostOption: "FALSE",
      categoryCode: 71,
      categoryDescription: "Exterior Lights"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223857,
      ruleType: "RA",
      optionCode: 118097,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 554.17,
      vat: 110.83,
      defaultOption: 0,
      description:
        "Lane assist with dynamic light assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223858,
      ruleType: "RA",
      optionCode: 117649,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 291.67,
      vat: 58.33,
      defaultOption: 0,
      description: "LED headlights with dynamic light assist",
      nonSpecificCostOption: "FALSE",
      categoryCode: 71,
      categoryDescription: "Exterior Lights"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223858,
      ruleType: "RA",
      optionCode: 118098,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1033.33,
      vat: 206.67,
      defaultOption: 0,
      description:
        "Lane assist plus with dynamic light assist, emergency assist, rear traffic alert, side scan, traffic jam assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223859,
      ruleType: "IN",
      optionCode: 87501,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 179.17,
      vat: 35.83,
      defaultOption: 0,
      description: "High beam assist",
      nonSpecificCostOption: "FALSE",
      categoryCode: 71,
      categoryDescription: "Exterior Lights"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223859,
      ruleType: "IN",
      optionCode: 118099,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 945.83,
      vat: 189.17,
      defaultOption: 0,
      description:
        "Lane assist plus with emergency assist, high beam assist, rear traffic alert, side scan, traffic jam assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223860,
      ruleType: "NW",
      optionCode: 87501,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 179.17,
      vat: 35.83,
      defaultOption: 0,
      description: "High beam assist",
      nonSpecificCostOption: "FALSE",
      categoryCode: 71,
      categoryDescription: "Exterior Lights"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223860,
      ruleType: "NW",
      optionCode: 117649,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 291.67,
      vat: 58.33,
      defaultOption: 0,
      description: "LED headlights with dynamic light assist",
      nonSpecificCostOption: "FALSE",
      categoryCode: 71,
      categoryDescription: "Exterior Lights"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223860,
      ruleType: "NW",
      optionCode: 118097,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 554.17,
      vat: 110.83,
      defaultOption: 0,
      description:
        "Lane assist with dynamic light assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223860,
      ruleType: "NW",
      optionCode: 118098,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1033.33,
      vat: 206.67,
      defaultOption: 0,
      description:
        "Lane assist plus with dynamic light assist, emergency assist, rear traffic alert, side scan, traffic jam assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223861,
      ruleType: "RA",
      optionCode: 108763,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 729.17,
      vat: 145.83,
      defaultOption: 0,
      description: "Trailer assist steering with park assist",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223861,
      ruleType: "RA",
      optionCode: 133047,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 604.17,
      vat: 120.83,
      defaultOption: 0,
      description: "Towbar swivelling with 13 pin connection",
      nonSpecificCostOption: "FALSE",
      categoryCode: 79,
      categoryDescription: "Towing"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223862,
      ruleType: "NW",
      optionCode: 127828,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1250,
      vat: 250,
      defaultOption: 0,
      description:
        "Discover DVD navigation pro, 9.2 touch screen European map data",
      nonSpecificCostOption: "64GB HDD + voice control",
      categoryCode: "Radio/DVD",
      categoryDescription: "Gesture control"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223862,
      ruleType: "NW",
      optionCode: 127846,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description: "Discover navigation, 8colour touch screen",
      nonSpecificCostOption: "2D/3D European map data",
      categoryCode: "Radio/CD",
      categoryDescription: "infotainment system via smartphone or tablet"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223862,
      ruleType: "NW",
      optionCode: 133034,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description:
        "Car net app connect combined functionality of Apple CarPlay, Android Auto and MirrorLink, USB connection, audio and voice control",
      nonSpecificCostOption: "FALSE",
      categoryCode: 68,
      categoryDescription: "Communication"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223863,
      ruleType: "IN",
      optionCode: 99096,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 208.33,
      vat: 41.67,
      defaultOption: 0,
      description: "Voice activation for telephone and navigation",
      nonSpecificCostOption: "FALSE",
      categoryCode: 68,
      categoryDescription: "Communication"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223863,
      ruleType: "IN",
      optionCode: 127828,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1250,
      vat: 250,
      defaultOption: 0,
      description:
        "Discover DVD navigation pro, 9.2 touch screen European map data",
      nonSpecificCostOption: "64GB HDD + voice control",
      categoryCode: "Radio/DVD",
      categoryDescription: "Gesture control"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223864,
      ruleType: "OO",
      optionCode: 127868,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 158.33,
      vat: 31.67,
      defaultOption: 0,
      description:
        "Multifunction heated leather trimmed steering wheel with gear knob",
      nonSpecificCostOption: "FALSE",
      categoryCode: 61,
      categoryDescription: "Interior Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223864,
      ruleType: "OO",
      optionCode: 127869,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 320.83,
      vat: 64.17,
      defaultOption: 0,
      description:
        "Multifunction heated leather trimmed steering wheel with gear knob including paddle shift",
      nonSpecificCostOption: "FALSE",
      categoryCode: 61,
      categoryDescription: "Interior Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223864,
      ruleType: "OO",
      optionCode: 127942,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 162.5,
      vat: 32.5,
      defaultOption: 0,
      description:
        "Multifunction leather steering wheel with leather trimmed gear knob including paddle shift",
      nonSpecificCostOption: "FALSE",
      categoryCode: 61,
      categoryDescription: "Interior Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223864,
      ruleType: "OO",
      optionCode: 127967,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description:
        "Multifunction leather steering wheel with leather trimmed gear knob",
      nonSpecificCostOption: "FALSE",
      categoryCode: 61,
      categoryDescription: "Interior Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223865,
      ruleType: "RO",
      optionCode: 95052,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1791.67,
      vat: 358.33,
      defaultOption: 0,
      description:
        "Vienna leather upholstery + perforated heated front sports seats with manually adjustable lumbar support",
      nonSpecificCostOption: "TRUE",
      categoryCode: 61,
      categoryDescription: "Interior Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223865,
      ruleType: "RO",
      optionCode: 95055,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1791.67,
      vat: 358.33,
      defaultOption: 0,
      description:
        "Vienna leather - Black + heated front sports seats with lumbar support",
      nonSpecificCostOption: "FALSE",
      categoryCode: 82,
      categoryDescription: "Trim - Leather"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223865,
      ruleType: "RO",
      optionCode: 133044,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 512.5,
      vat: 102.5,
      defaultOption: 0,
      description:
        "Electrically adjustable driver's seat with memory function for personal settings and electrically adjustable lumbar support",
      nonSpecificCostOption: "FALSE",
      categoryCode: 49,
      categoryDescription: "Seats"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223866,
      ruleType: "NW",
      optionCode: 95052,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1791.67,
      vat: 358.33,
      defaultOption: 0,
      description:
        "Vienna leather upholstery + perforated heated front sports seats with manually adjustable lumbar support",
      nonSpecificCostOption: "TRUE",
      categoryCode: 61,
      categoryDescription: "Interior Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223866,
      ruleType: "NW",
      optionCode: 95055,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1791.67,
      vat: 358.33,
      defaultOption: 0,
      description:
        "Vienna leather - Black + heated front sports seats with lumbar support",
      nonSpecificCostOption: "FALSE",
      categoryCode: 82,
      categoryDescription: "Trim - Leather"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223866,
      ruleType: "NW",
      optionCode: 133045,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 145.83,
      vat: 29.17,
      defaultOption: 0,
      description:
        "Folding front seat backrest release on front passenger seat",
      nonSpecificCostOption: "FALSE",
      categoryCode: 49,
      categoryDescription: "Seats"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223867,
      ruleType: "OO",
      optionCode: 12003,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description: "Front cupholders x 2",
      nonSpecificCostOption: "FALSE",
      categoryCode: 61,
      categoryDescription: "Interior Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223867,
      ruleType: "OO",
      optionCode: 72575,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 41.67,
      vat: 8.33,
      defaultOption: 0,
      description: "Smoking pack - Golf",
      nonSpecificCostOption: "FALSE",
      categoryCode: 34,
      categoryDescription: "Packs"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223868,
      ruleType: "IN",
      optionCode: 87501,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 179.17,
      vat: 35.83,
      defaultOption: 0,
      description: "High beam assist",
      nonSpecificCostOption: "FALSE",
      categoryCode: 71,
      categoryDescription: "Exterior Lights"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223868,
      ruleType: "IN",
      optionCode: 118096,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 470.83,
      vat: 94.17,
      defaultOption: 0,
      description:
        "Lane assist + High beam assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223869,
      ruleType: "OO",
      optionCode: 63647,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description:
        "Ultrasonic front and rear optical and audible parking sensors",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223869,
      ruleType: "OO",
      optionCode: 133035,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 500,
      vat: 100,
      defaultOption: 0,
      description:
        "Park assist sensor controlled steering aid to assist parallel or bay parking features optical parking display via vehicle's infotainment system",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223871,
      ruleType: "NW",
      optionCode: 95052,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1791.67,
      vat: 358.33,
      defaultOption: 0,
      description:
        "Vienna leather upholstery + perforated heated front sports seats with manually adjustable lumbar support",
      nonSpecificCostOption: "TRUE",
      categoryCode: 61,
      categoryDescription: "Interior Features"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223871,
      ruleType: "NW",
      optionCode: 95055,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1791.67,
      vat: 358.33,
      defaultOption: 0,
      description:
        "Vienna leather - Black + heated front sports seats with lumbar support",
      nonSpecificCostOption: "FALSE",
      categoryCode: 82,
      categoryDescription: "Trim - Leather"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223871,
      ruleType: "NW",
      optionCode: 132397,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description: "Front comfort seats with height and lumbar adjustment",
      nonSpecificCostOption: "FALSE",
      categoryCode: 49,
      categoryDescription: "Seats"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223871,
      ruleType: "NW",
      optionCode: 133044,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 512.5,
      vat: 102.5,
      defaultOption: 0,
      description:
        "Electrically adjustable driver's seat with memory function for personal settings and electrically adjustable lumbar support",
      nonSpecificCostOption: "FALSE",
      categoryCode: 49,
      categoryDescription: "Seats"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223872,
      ruleType: "OO",
      optionCode: 54516,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description: "Remote central locking with 2 remote folding keys",
      nonSpecificCostOption: "FALSE",
      categoryCode: 48,
      categoryDescription: "Security"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223872,
      ruleType: "OO",
      optionCode: 127883,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 325,
      vat: 65,
      defaultOption: 0,
      description: "Keyless entry with start/stop button on centre console",
      nonSpecificCostOption: "FALSE",
      categoryCode: 48,
      categoryDescription: "Security"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223873,
      ruleType: "NW",
      optionCode: 10690,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description: "8 speakers",
      nonSpecificCostOption: "FALSE",
      categoryCode: 24,
      categoryDescription: "Entertainment"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223873,
      ruleType: "NW",
      optionCode: 108853,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 500,
      vat: 100,
      defaultOption: 0,
      description: "Dynaudio excite sound pack - Golf",
      nonSpecificCostOption: "FALSE",
      categoryCode: 34,
      categoryDescription: "Packs"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223873,
      ruleType: "NW",
      optionCode: 133119,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description: "4 X 20 watt output",
      nonSpecificCostOption: "FALSE",
      categoryCode: 24,
      categoryDescription: "Entertainment"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223874,
      ruleType: "RO",
      optionCode: 117649,
      isPrimary: true,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 291.67,
      vat: 58.33,
      defaultOption: 0,
      description: "LED headlights with dynamic light assist",
      nonSpecificCostOption: "FALSE",
      categoryCode: 71,
      categoryDescription: "Exterior Lights"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223874,
      ruleType: "RO",
      optionCode: 118097,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 554.17,
      vat: 110.83,
      defaultOption: 0,
      description:
        "Lane assist with dynamic light assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223874,
      ruleType: "RO",
      optionCode: 118098,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 1033.33,
      vat: 206.67,
      defaultOption: 0,
      description:
        "Lane assist plus with dynamic light assist, emergency assist, rear traffic alert, side scan, traffic jam assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223875,
      ruleType: "OO",
      optionCode: 117648,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 291.67,
      vat: 58.33,
      defaultOption: 0,
      description: "LED headlights with dynamic curve lighting",
      nonSpecificCostOption: "FALSE",
      categoryCode: 71,
      categoryDescription: "Exterior Lights"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7223875,
      ruleType: "OO",
      optionCode: 118096,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 470.83,
      vat: 94.17,
      defaultOption: 0,
      description:
        "Lane assist + High beam assist and traffic sign recognition",
      nonSpecificCostOption: "FALSE",
      categoryCode: 67,
      categoryDescription: "Driver Aids"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7224046,
      ruleType: "OO",
      optionCode: 125866,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 0,
      vat: 0,
      defaultOption: 1,
      description: "Car information display",
      nonSpecificCostOption: "FALSE",
      categoryCode: 66,
      categoryDescription: "Driver Information"
    },
    {
      id: 91341,
      capcode: "VWGO20ME 5EDTA  6",
      name: "2.0 TDI Match Edition 5dr DSG",
      introduced: "2019-10-01",
      discontinued: "NULL",
      periodCode: 340066,
      periodEffectiveFrom: "2019-12-14",
      periodEffectiveTo: "NULL",
      ruleCode: 7224046,
      ruleType: "OO",
      optionCode: 133036,
      isPrimary: false,
      optionEffectiveFrom: "2019-10-01",
      optionEffectiveTo: "NULL",
      basicPrice: 437.5,
      vat: 87.5,
      defaultOption: 0,
      description:
        "Active information display - 12.3 high resolution TFT display",
      nonSpecificCostOption: "FALSE",
      categoryCode: 66,
      categoryDescription: "Driver Information"
    }
  ]
};
